export const areas=[
"Abdalian Housing Society",
"Abu Bakar Block",
"Ahmed Block"	,
"Aibak Block"	,
"Airline Society"	,
"Airport Road"	,
"Aitchison Society"	,
"Alfalah Town"	,
"Ali Block"	,
"Ali Park"	,
"Allama Iqbal Medical College"	,
"Allama Iqbal Town"	,
"Alpha Co Operative"	,
"Amin Park"	,
"Anar Kali"	,
"Architects Engineers Society"	,
"Army Housing Society"	,
"Asif Block"	,
"Askari Colony"	,
"Askrai Villa"	,
"Askrai Villa 1"	,
"Askrai Villa 10"	,
"Askrai Villa 2"	,
"Askrai Villa 3"	,
"Askrai Villa 4"	,
"Askrai Villa 5"	,
"Askrai Villa 6"	,
"Askrai Villa 7"	,
"Askrai Villa 8"	,
"Askrai Villa 9"	,
"Atta Turk Block"	,
"Aurangzeb Block"	,
"Awan Market"	,
"Awan Town"	,
"Baba Farid Colony"	,
"Babar Block"	,
"Badami Bagh"	,
"Badar Block"	,
"Baghban Pura"	,
"Bagrian"	,
"Bahria Town"	,
"Band Road"	,
"Barki Road"	,
"Bedian Road"	,
"Bilal Gang"	,
"Bostan Colony"	,
"Bridge Colony"	,
"Burj Colony"	,
"Canal Bank"	,
"Canal Breeze"	,
"Canal Garden"	,
"Canal Park Society"	,
"Canal Road"	,
"Canal View Colony"	,
"Cantt"	,
"Cavalry Ground"	,
"Chachowali"	,
"Chararrd Village"	,
"Chenab Block"	,
"Chungi Amer Sadhu"	,
"Civic Center"	,
"CMA Colony"	,
"College Block"	,
"Darbar Gurreh Shah"	,
"Data Nagar"	,
"Davis Road"	,
"DHA 1"	,
"DHA 2"	,
"DHA 3"	,
"DHA 4"	,
"DHA 5"	,
"DHA 6"	,
"DHA 7"	,
"DHA 8"	,
"Dharampura"	,
"Doctors Society"	,
"Eden Avenue"	,
"Eden Canal Villas"	,
"Eden Homes"	,
"Eden View"	,
"Education Town"	,
"EME DHA Society"	,
"Engineer Cooperative Society"	,
"Faisal Town"	,
"Falcon Complex"	,
"Faruque Ganj"	,
"Fc College"	,
"Ferozpur Road"	,
"Firozpur Road"	,
"Fort Villas"	,
"Fortress Stadium"	,
"Fransisi Town"	,
"Ganga Ram Hospital"	,
"Garden Block"	,
"Garhi Shahu"	,
"Gawal Mandi"	,
"Ghazi Road"	,
"Ghousia Colony"	,
"Gohawa"	,
"Gor"	,
"Gor I"	,
"Gor II"	,
"Gor III"	,
"Gor IV"	,
"Gor V"	,
"Green Town"	,
"Gulbahar Colony"	,
"Gulberg 1"	,
"Gulberg 2"	,
"Gulberg 3"	,
"Gulberg 4"	,
"Gulberg 5"	,
"Guldasit Colony"	,
"Gulshan Block"	,
"Gulshan E Ravi"	,
"Hamdard Chowk"	,
"Herbuns Pura"	,
"Huma Block",
"Hunza Block"	,
"Ichhra"	,
"Infantry Road"	,
"Iqbal Ave Housing Society"	,
"Iqbal Avenue"	,
"Islam Pura"	,
"Ittehad Colony"	,
"Izmir Town"	,
"Jail Road"	,
"Jehanzeb Block"	,
"Jinnah Hospital"	,
"Johar Town"	,
"Jubli Town"	,
"K B Society"	,
"Kainchi"	,
"Kamran Block"	,
"Karim Block"	,
"Karim Park"	,
"Khuda Buksh Colony"	,
"Khudad Town"	,
"Khursheed Alam Road"	,
"Khyaban E Amin"	,
"Khyber Block"	,
"Kot Lakhpat"	,
"Lahore Gym Khana"	,
"Lake City"	,
"Lakshmi Chowk"	,
"Lalzar Colony"	,
"Lawrence Road"	,
"LDA Avenue"	,
"LDA Colony"	,
"Lidhar"	,
"LUMS"	,
"M M Alam Road"	,
"Madina Colony"	,
"Mahmood Booty Ring Road"	,
"Main Gulberg Boulevard"	,
"Main Khayaban Road"	,
"Main Mir Colony"	,
"Makkah Colony"	,
"Mall Road"	,
"Mamdoot Block"	,
"Maraghzar Colony"	,
"Mayo Hospital"	,
"Mazang"	,
"Mehran Block"	,
"Misri Shah"	,
"Model Town"	,
"Moon Market"	,
"Mughal Pura"	,
"Muhafiz Town"	,
"Multan Road"	,
"Munir Road"	,
"Muslim Town"	,
"Muslima Bad"	,
"Mustafa Bad"	,
"Mustafa Town"	,
"Nabi Pura"	,
"Nargis Block"	,
"Nasheman Colony"	,
"Nasheman Iqbal Housing Scheme"	,
"Neelam Block"	,
"Nespak Society"	,
"New Garden Town"	,
"New Mustafa Colony"	,
"New PAF Colony"	,
"NFC Town"	,
"Nisar Colony"	,
"Nishtar Block"	,
"Nishtar Colony"	,
"Nizam Block"	,
"Officers Colony"	,
"Opf Colony"	,
"Opf Housing Scheme"	,
"Pak Block"	,
"Paragon City"	,
"PASCO Housing Society"	,
"PCSIR Housing Scheme"	,
"PCSIR Housing Society"	,
"PCSIR Society"	,
"Peco Road"	,
"PIA Society"	,
"Punjab Govt Employs Coparative Society"	,
"Punjab Society Near Dha"	,
"Punjab University"	,
"Punjab University Hostel"	,
"Punjab University Old Campus"	,
"Qila Gujarsing"	,
"Quaid e Azam Industrial Estate"	,
"R A Bazaar"	,
"Race Course Park Surrounding Area"	,
"Race Course Town"	,
"Rachna Block"	,
"Railway Housing Society"	,
"Raiwind Road"	,
"Ram Garh"	,
"Rang Mehal"	,
"Ravi Block"	,
"Ravi Road"	,
"Raza Block"	,
"Rehman Garden"	,
"Revenue Society"	,
"Riwaz Garden"	,
"Sabzazar"	,
"Saddar"	,
"Saidpur"	,
"Saint John Park"	,
"Salamatpura"	,
"Samanabad"	,
"Samia Town"	,
"Sanat Nagar"	,
"Sanda Kalan"	,
"Sanda Khurd"	,
"Sarshar Town"	,
"Sarwar Road"	,
"Shabir Town"	,
"Shad Bagh"	,
"Shadman Colony"	,
"Shah Jamal"	,
"Shahtaj Colony"	,
"Shaikh Zayed Hospital"	,
"Shalimar Link Road"	,
"Shalimar Town"	,
"Shama Colony"	,
"Shaukat Khanum Hospital"	,
"Shersha Block"	,
"Sikandar Block"	,
"Star Town"	,
"State Life Society"	,
"Sui Gas Society"	,
"Sukh Chain Society"	,
"Suparco Colony"	,
"Super Town"	,
"Sutlej Block"	,
"Taj Bagh"	,
"Taj Para"	,
"Tariq Block"	,
"Tariq Garden"	,
"Tech Society"	,
"Temple Road"	,
"Thokar Niaz Baig"	,
"Tipu Block"	,
"Township"	,
"Tricon Valley"	,
"Tufail Road"	,
"UCP"	,
"Umer Block"	,
"University of Lahore"	,
"Upper Mall Scheme"	,
"Usman Block"	,
"Usman Ganj"	,
"Valencia Town Block A1"	,
"Valencia Town Block A2"	,
"Valencia Town Block A3"	,
"Valencia Town Block C"	,
"Valencia Town Block F"	,
"Valencia Town Block G"	,
"Valencia Town Block H"	,
"Valencia Town Block H1"	,
"Valencia Town Block J"	,
"Valencia Town Block K1"	,
"Valencia Town Block L"	,
"Valencia Town Block P1"	,
"Wafaqi Colony"	,
"Wahdat Colony"	,
"Walton Road"	,
"Wapda Colony"	,
"Wapda House"	,
"Wapda Town"	,
"West Wood Colony "	,
"Youhna Bad"	,
"Zaman Colony"	,
"Zeenat Block"	
]
export default areas;